# Generated by Django 4.0.5 on 2022-06-29 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.CharField(choices=[('', 'Choose...'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50)),
                ('genotype', models.CharField(choices=[('', 'Choose...'), ('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC')], max_length=50)),
                ('sex', models.CharField(choices=[('', 'Choose...'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=700)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zipcode', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('will_donate', models.CharField(choices=[('', 'Choose...'), ('Yes, I will Donate', 'Yes, I will Donate'), ('No, Some other Time', 'No, Some other Time')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
